export const fileExtensions = {
  jpg: "image",
  jpeg: "image",
  png: "image",
  gif: "image",
  webp: "image",
  bmp: "image",
  tiff: "image",
  tif: "image",
  heic: "image",
  heif: "image",
  ico: "image",
  svg: "image",

  mp4: "video",
  mov: "video",
  avi: "video",
  mkv: "video",
  flv: "video",
  wmv: "video",
  webm: "video",
  m4v: "video",
  "3gp": "video",
  mpeg: "video",
  mpg: "video",

  mp3: "video",
  wav: "video",
  m4a: "video",
  aac: "video",
  ogg: "video",
  oga: "video",
  flac: "video",
  aiff: "video",
  wma: "video",
  opus: "video",
  mid: "video",
  midi: "video",

  doc: "raw",
  pdf: "raw",
  docx: "raw",
  xls: "raw",
  xlsx: "raw",
  ppt: "raw",
  pptx: "raw",
  txt: "raw",
  rtf: "raw",
  csv: "raw",
  json: "raw",
  xml: "raw",
  md: "raw",

  zip: "raw",
  rar: "raw",
  "7z": "raw",
  tar: "raw",
  gz: "raw",
  bz2: "raw",

  js: "raw",
  ts: "raw",
  jsx: "raw",
  tsx: "raw",
  html: "raw",
  css: "raw",
  py: "raw",
  java: "raw",
  cpp: "raw",
  c: "raw",
  cs: "raw",
  php: "raw",
  json: "raw"
};
